server.port=9006
#management.server.port=9855
#management.server.address=127.0.0.1
#spring.boot.admin.client.url=http://127.0.0.1:9001/
#management.endpoints.web.exposure.include=*


#spring.datasource.url=jdbc:postgresql://192.168.0.186:5432/
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://192.168.0.186:5432/}
spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.password=${POSTGRES_PWD:postgres}
spring.jpa.show-sql=true

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update